name = "brioche"
version = "1.0.0"
target = "javascript"

description = "Bun bindings for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "ghivert", repo = "brioche" }
gleam = ">= 1.9.0 and < 2.0.0"
internal_modules = ["brioche/internals.gleam", "brioche/internals/*"]
# links = [{ title = "Website", href = "" }]

[javascript]
typescript_declarations = true
runtime = "bun"

[dependencies]
gleam_fetch = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
bigi = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
exception = ">= 2.0.0 and < 3.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
